
/*
 * MenuPrincipal.java
 *
 * Created on 25/08/2011, 19:11:00
 */
package view;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import mensageiros.Mensageiro;
import utils.Auxiliador;
import utils.JTableRenderer;

/**
 *
 * @author Siloe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    Mensageiro controlador;
    String usuario = "padrao";

    /** Creates new form MenuPrincipal */
    public MenuPrincipal(Mensageiro m) {
        try {
            //Muda design da tela
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        this.controlador = (Mensageiro) m;

        //Exibe os arquivos
        mostrarArquivos();
    }

//    public void mostrarArquivos() {
//        try {
//            arquivosPanel.removeAll();
//            File flist[] = controlador.pegarArquivos(usuario);
//            for (File file : flist) {
//                String nomeDoArquivo = file.getName();
//                Auxiliador.addVizualizacaoDoArquivo(arquivosPanel, nomeDoArquivo);
//                System.out.println("Exibindo arquivo: " + file);
//            }
//            
//            arquivosPanel.repaint();
//        } catch (RemoteException ex) {
//            ex.printStackTrace();
//        }
//    }
    public void mostrarArquivos() {
        try {
            ((DefaultTableModel) arquivosTable.getModel()).setRowCount(0);
            File flist[] = controlador.pegarArquivos(usuario);

            for (File file : flist) {
                Auxiliador.addVizualizacaoDoArquivo(arquivosTable, file.getName());
            }


        } catch (RemoteException ex) {
            ex.printStackTrace();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraDeBotoes = new javax.swing.JPanel();
        criarTxtButton = new javax.swing.JButton();
        editarTxtButton = new javax.swing.JButton();
        subirButton = new javax.swing.JButton();
        baixarButton = new javax.swing.JButton();
        executarButton = new javax.swing.JButton();
        atualizarButton = new javax.swing.JButton();
        excluirButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        arquivosTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GerArq");
        setLocationByPlatform(true);

        barraDeBotoes.setBackground(new java.awt.Color(0, 51, 255));
        barraDeBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 51), null));

        criarTxtButton.setText("Criar arquivo de texto");
        criarTxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarTxtButtonActionPerformed(evt);
            }
        });

        editarTxtButton.setText("Editar arquivo de texto");
        editarTxtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarTxtButtonActionPerformed(evt);
            }
        });

        subirButton.setText("Subir arquivo");
        subirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subirButtonActionPerformed(evt);
            }
        });

        baixarButton.setText("Baixar arquivo");
        baixarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baixarButtonActionPerformed(evt);
            }
        });

        executarButton.setText("Executar");
        executarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executarButtonActionPerformed(evt);
            }
        });

        atualizarButton.setText("Atualizar");

        excluirButton.setText("Excluir");
        excluirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout barraDeBotoesLayout = new javax.swing.GroupLayout(barraDeBotoes);
        barraDeBotoes.setLayout(barraDeBotoesLayout);
        barraDeBotoesLayout.setHorizontalGroup(
            barraDeBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(barraDeBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(criarTxtButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(baixarButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(executarButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(editarTxtButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subirButton, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(excluirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(atualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap())
        );
        barraDeBotoesLayout.setVerticalGroup(
            barraDeBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barraDeBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(criarTxtButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarTxtButton, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(baixarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(executarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(excluirButton, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(atualizarButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );

        arquivosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo de arquivo", "Nome do arquivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        arquivosTable.setRowHeight(48);
        jScrollPane1.setViewportView(arquivosTable);
        arquivosTable.getColumnModel().getColumn(0).setMinWidth(60);
        arquivosTable.getColumnModel().getColumn(0).setPreferredWidth(60);
        arquivosTable.getColumnModel().getColumn(0).setMaxWidth(60);
        TableColumnModel columnModel = arquivosTable.getColumnModel();
        JTableRenderer renderer = new JTableRenderer();
        columnModel.getColumn(0).setCellRenderer(renderer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(barraDeBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(barraDeBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void criarTxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarTxtButtonActionPerformed
    try {
        controlador.criarArquivosDeTexto(usuario);
    } catch (RemoteException ex) {
        JOptionPane.showMessageDialog(null,
                "Não foi possiver criar o arquivo devido à um problema de conexão",
                "ERRO", JOptionPane.ERROR_MESSAGE);
    }

    mostrarArquivos();
}//GEN-LAST:event_criarTxtButtonActionPerformed

private void subirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subirButtonActionPerformed
    try {
        controlador.subirArquivos(usuario);
    } catch (RemoteException ex) {
        JOptionPane.showMessageDialog(null,
                "Não foi possiver subir o arquivo devido à um problema de conexão",
                "ERRO", JOptionPane.ERROR_MESSAGE);
    }

    mostrarArquivos();

}//GEN-LAST:event_subirButtonActionPerformed

private void baixarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baixarButtonActionPerformed
    try {
        byte[] b = controlador.baixarArquivos(usuario, "" + arquivosTable.getValueAt(arquivosTable.getSelectedRow(), 1));
        File file = Auxiliador.pegarNomeDoArquivo(); //Criamos um nome para o arquivo  
        if (file != null) {
            BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream(file)); //Criamos o arquivo  
            bos.write(b); //Gravamos os bytes lá  
            bos.close(); //Fechamos o stream.  
        }
    } catch (IOException ex) {
        ex.printStackTrace();
    }
}//GEN-LAST:event_baixarButtonActionPerformed

private void executarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executarButtonActionPerformed
    String diretorio = usuario + "\\" + arquivosTable.getValueAt(arquivosTable.getSelectedRow(), 1);
    Auxiliador.executarArquivo(usuario + "\\" + arquivosTable.getValueAt(arquivosTable.getSelectedRow(), 1));

}//GEN-LAST:event_executarButtonActionPerformed

private void excluirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirButtonActionPerformed
    try {
        controlador.execluirArquivos(usuario, "" + arquivosTable.getValueAt(arquivosTable.getSelectedRow(), 1));
    } catch (RemoteException ex) {
        JOptionPane.showMessageDialog(null,
                "Não foi possiver excluir o arquivo devido à um problema de conexão",
                "ERRO", JOptionPane.ERROR_MESSAGE);
    }
    mostrarArquivos();
}//GEN-LAST:event_excluirButtonActionPerformed

private void editarTxtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarTxtButtonActionPerformed
    
}//GEN-LAST:event_editarTxtButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable arquivosTable;
    private javax.swing.JButton atualizarButton;
    private javax.swing.JButton baixarButton;
    private javax.swing.JPanel barraDeBotoes;
    private javax.swing.JButton criarTxtButton;
    private javax.swing.JButton editarTxtButton;
    private javax.swing.JButton excluirButton;
    private javax.swing.JButton executarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton subirButton;
    // End of variables declaration//GEN-END:variables
}
