/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDesenho.java
 *
 * Created on 01/03/2011, 18:38:37
 */

package visual;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Stroke;
import javax.swing.JPanel;

/**
 *
 * @author douglas
 */
public class JDesenho extends JPanel {

    /** Creates new form JDesenho */
    public JDesenho() {
        initComponents();
    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g.create();
        
        //g2d.setColor(Color.BLACK);
        
        g2d.setStroke(new BasicStroke(3));
        //g2d.drawRect(0, 0, 400, 275);
        g2d.drawLine(102, 30, 102, 380);// linha vertical da esquerda
        g2d.drawLine(200, 30, 200, 380);// linha vertical da direita
        g2d.drawLine(5, 150, 295, 150);//Linha horizontal de cima
        g2d.drawLine(5, 255, 295, 255);//Linha horizontal de baixo
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
